// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://qwertyuiopasdfghjklz.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = '{{fake:supabase-anon-jwt}}';

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
