#!/usr/bin/env node
// Generates documentation from its sources, so the docs cannot drift:
//   docs/rules/<pack>/<name>.md   one page per rule, from the rule metadata and its fixtures
//   docs/rules/README.md          the rule index
//   src/data/examples.ts          the examples that `ubon explain` prints
//   README.md (demo block)        the output of `ubon check` on fixtures/demo
//   llms.txt, llms-full.txt       an index of the docs for language models, and all of their text
// Usage: node scripts/gen-docs.mjs [--check]
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const root = join(import.meta.dirname, '..');
const check = process.argv.includes('--check');
const REPO = 'https://github.com/luisfer/ubon';
const BLOB = `${REPO}/blob/main`;

const { RULES } = await import('../src/rules/index.ts');
const { listFixtureCases, readExpectations } = await import('../test/support/rule-tester.ts');
const { fakeKey } = await import('../test/support/fake-keys.ts');
const { maskSecrets } = await import('../src/core/mask.ts');
const { listFilesRecursive } = await import('../test/support/fixtures.ts');

const outputs = new Map();
const GENERATED = '<!-- Generated by scripts/gen-docs.mjs from the rule metadata and fixtures. Do not edit; run `npm run gen`. -->';

// ---------------------------------------------------------------------------
// Examples from fixtures

const FAKE = /\{\{fake:([a-z0-9-]+)(?::(\d+))?\}\}/g;
function showFakes(text) {
  return text.replace(FAKE, (_m, id, n) => {
    const key = fakeKey(id, n ? Number(n) : 1);
    const masked = maskSecrets(key);
    return masked !== key ? masked : `<${id}>`;
  });
}

const MARKER = String.raw`(?:expect(?:-warn|-block)?|ok):`;
function stripMarkers(line) {
  return line
    .replace(new RegExp(String.raw`\s*\{\s*/\*\s*${MARKER}.*?\*/\s*\}`), '')
    .replace(new RegExp(String.raw`\s*/\*\s*${MARKER}.*?\*/`), '')
    .replace(new RegExp(String.raw`\s*<!--\s*${MARKER}.*?-->`), '')
    .replace(new RegExp(String.raw`\s*(//|#|--|;)\s*${MARKER}.*$`), '')
    .trimEnd();
}

function okReason(line) {
  const m = /\bok:\s*(.+?)\s*(\*\/\s*\}?|-->)?\s*$/.exec(line);
  return m ? m[1] : null;
}

function isCommentOnly(line) {
  return /^\s*(\/\/|#|--|<!--|\/\*|\*|\{\s*\/\*)/.test(line);
}

const LANG = { ts: 'ts', tsx: 'tsx', js: 'js', jsx: 'jsx', mjs: 'js', cjs: 'js', mts: 'ts', cts: 'ts', json: 'json', jsonc: 'jsonc', yml: 'yaml', yaml: 'yaml', sql: 'sql', md: 'md', toml: 'toml', sh: 'sh', vue: 'vue', svelte: 'svelte', astro: 'astro', py: 'python', rules: 'text' };
function fenceLang(file) {
  const base = file.split('/').pop() ?? file;
  if (base.startsWith('.env')) return 'sh';
  if (base === 'Dockerfile') return 'dockerfile';
  const ext = base.includes('.') ? base.split('.').pop() : '';
  return LANG[ext] ?? 'text';
}

function collectExamples(rule) {
  const flagged = [];
  const safe = [];
  for (const c of listFixtureCases().filter((f) => f.rule === rule)) {
    const isDiff = existsSync(join(c.dir, 'before')) && existsSync(join(c.dir, 'after'));
    const dir = isDiff ? join(c.dir, 'after') : c.dir;
    const { expected } = readExpectations(dir, rule);
    for (const e of expected) {
      const lines = readFileSync(join(dir, e.file), 'utf8').split('\n');
      const code = showFakes(stripMarkers(lines[e.line - 1] ?? '')).trim();
      if (code) flagged.push({ file: e.file, code, ...(e.level ? { level: e.level } : {}) });
    }
    for (const file of listFilesRecursive(dir)) {
      if (file === 'fixture.json' || file === 'expect.json') continue;
      const lines = readFileSync(join(dir, file), 'utf8').split('\n');
      lines.forEach((line, i) => {
        const reason = okReason(line);
        if (!reason) return;
        let code = stripMarkers(line).trim();
        if (!code || isCommentOnly(code)) {
          const next = lines.slice(i + 1).find((l) => l.trim() !== '' && !isCommentOnly(l));
          code = next ? stripMarkers(next).trim() : '';
        }
        safe.push({ file, code: showFakes(code), note: reason });
      });
    }
    const sidecar = join(dir, 'expect.json');
    if (existsSync(sidecar)) {
      const data = JSON.parse(readFileSync(sidecar, 'utf8'));
      for (const reason of data.ok ?? []) safe.push({ file: '', code: '', note: reason });
    }
  }
  return { flagged: dedupe(flagged), safe: dedupe(safe) };
}

function dedupe(list) {
  const seen = new Set();
  return list.filter((e) => {
    const key = `${e.code}\u0000${e.note ?? ''}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

// ---------------------------------------------------------------------------
// Rule pages

const SCOPES = {
  file: 'each file in scope, on its own',
  project: 'the project as a whole, across files',
  diff: 'what the change did, comparing each file before and after',
  hook: 'agent actions in hooks: commands, file reads, and prompts',
};
const PACKS = {
  secret: 'Credentials in code, config, prompts, and tool output.',
  web: 'Trust boundaries in web code: request data reaching SQL, shells, file paths, URLs, and HTML, and routes without auth.',
  data: 'Data access policies: Supabase row level security, Firebase rules, and service keys.',
  llm: 'Features built on language models: keys in the browser, model output reaching code or queries, and tools with too much power.',
  deps: 'Packages an agent adds: whether they exist, their age, their names, and their install scripts.',
  agent: 'Agent configuration, instruction files, and the commands agents run.',
  ci: 'CI workflows: untrusted input, permissions, pinning, and secrets.',
  integrity: 'Changes that weaken the checks: skipped or deleted tests, disabled type checks, lowered thresholds, and suppressions.',
  hygiene: 'Smaller mistakes that tend to reach production.',
};

function refLinks(meta) {
  const out = [];
  for (const cwe of meta.cwe ?? []) {
    const n = /CWE-(\d+)/.exec(cwe)?.[1];
    out.push(n ? `[${cwe}](https://cwe.mitre.org/data/definitions/${n}.html)` : cwe);
  }
  for (const o of meta.owasp ?? []) out.push(`OWASP ${o}`);
  for (const r of meta.references ?? []) out.push(r.startsWith('http') ? `<${r}>` : r);
  return out;
}

function rulePage(rule, examples) {
  const m = rule.meta;
  const lines = [GENERATED, '', `# ${m.id}`, '', `${m.title}.`, '', m.summary, ''];
  lines.push(`- Default level: \`${m.level}\`.`);
  if (m.levels) lines.push(`- Levels: ${m.levels.replace(/\.$/, '')}.`);
  lines.push(`- Looks at: ${SCOPES[m.scope] ?? m.scope}.`);
  const refs = refLinks(m);
  if (refs.length > 0) lines.push(`- References: ${refs.join(', ')}.`);
  lines.push('', '## Why it matters', '', m.why, '');
  if (examples.flagged.length > 0) {
    lines.push('## Flagged', '');
    for (const e of examples.flagged.slice(0, 8)) {
      lines.push(`\`${e.file}\`${e.level ? ` (${e.level})` : ''}:`, '', `\`\`\`${fenceLang(e.file)}`, e.code, '```', '');
    }
  }
  if (examples.safe.length > 0) {
    lines.push('## Not flagged', '');
    for (const e of examples.safe.slice(0, 10)) {
      if (e.code) lines.push(`- \`${e.code.replace(/`/g, "'")}\` in \`${e.file}\`: ${e.note}`);
      else lines.push(`- ${e.note}`);
    }
    lines.push('');
  }
  lines.push('## How to fix', '', m.fix, '');
  if (m.scope !== 'hook') {
    lines.push(
      '## If the finding is wrong',
      '',
      'Add a comment on the line above, in the comment syntax of the file, that says who decided and why:',
      '',
      '```',
      `ubon-ignore ${m.id}: <who decided>: <evidence>`,
      '```',
      '',
      `Or turn the rule off for the project in \`ubon.json\`: \`"rules": { "${m.id}": "off" }\`. See [configuration](../../config.md).`,
      '',
    );
  } else {
    lines.push('## If the check is wrong', '', `This check runs in agent hooks. Allow a command prefix with \`commands.allow\` in \`ubon.json\`, or set \`"rules": { "${m.id}": "off" }\`. See [configuration](../../config.md).`, '');
  }
  if (existsSync(join(root, 'fixtures/rules', m.id))) lines.push(`Fixtures: [fixtures/rules/${m.id}](../../../fixtures/rules/${m.id}).`, '');
  return lines.join('\n');
}

const examplesById = {};
const byPack = new Map();
for (const rule of RULES) {
  const id = rule.meta.id;
  const examples = collectExamples(id);
  examplesById[id] = examples;
  const [pack] = id.split('/');
  if (!byPack.has(pack)) byPack.set(pack, []);
  byPack.get(pack).push(rule);
  outputs.set(`docs/rules/${id}.md`, rulePage(rule, examples));
}

// Index
{
  const lines = [GENERATED, '', '# Rules', ''];
  lines.push(`Ubon has ${RULES.length} rules in ${byPack.size} packs. A \`block\` finding stops an agent from finishing and fails \`ubon check\`; a \`warn\` finding is reported and does not. \`ubon rules\` prints this list with the levels set in your \`ubon.json\`.`, '');
  for (const [pack, rules] of byPack) {
    lines.push(`## ${pack}`, '', PACKS[pack] ?? '', '', '| Rule | Level | What it catches |', '| --- | --- | --- |');
    for (const r of rules) lines.push(`| [${r.meta.id}](${r.meta.id}.md) | ${r.meta.level} | ${r.meta.title} |`);
    lines.push('');
  }
  outputs.set('docs/rules/README.md', lines.join('\n'));
}

// Examples for `ubon explain`
{
  const trimmed = {};
  for (const [id, ex] of Object.entries(examplesById)) {
    trimmed[id] = {
      flagged: ex.flagged.slice(0, 3).map(({ file, code }) => ({ file, code })),
      safe: ex.safe.filter((e) => e.code).slice(0, 3).map(({ file, code, note }) => ({ file, code, note })),
    };
  }
  const body = JSON.stringify(trimmed, null, 2);
  outputs.set(
    'src/data/examples.ts',
    `/**
 * Examples shown by \`ubon explain\`, extracted from the rule fixtures by
 * scripts/gen-docs.mjs. Do not edit by hand; run \`npm run gen\`.
 */

export interface RuleExample {
  file: string;
  code: string;
  note?: string;
}

export const EXAMPLES: Record<string, { flagged: RuleExample[]; safe: RuleExample[] }> = ${body};
`,
  );
}

// ---------------------------------------------------------------------------
// README demo: `ubon check` on fixtures/demo (before/ is the base commit, after/ the agent's changes)

async function demoOutput() {
  const { initRepo, commitAll, copyTree, replaceTree, tempDir, git } = await import('../test/support/fixtures.ts');
  const { expandFakeKeysInDir } = await import('../test/support/fake-keys.ts');
  const { runCheck } = await import('../src/core/engine.ts');
  const { formatText } = await import('../src/report/text.ts');
  const work = tempDir('ubon-demo-');
  try {
    initRepo(work);
    copyTree(join(root, 'fixtures/demo/before'), work);
    expandFakeKeysInDir(work);
    commitAll(work, 'base');
    git(work, 'checkout', '-q', '-b', 'agent-work');
    replaceTree(work, join(root, 'fixtures/demo/after'));
    expandFakeKeysInDir(work);
    const { report } = await runCheck({ cwd: work, mode: 'diff', useBaseline: false });
    const text = formatText(report, { color: false });
    const code = report.summary.block > 0 ? 1 : 0;
    return { text, code };
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}

{
  const readme = readFileSync(join(root, 'README.md'), 'utf8');
  const begin = '<!-- ubon:demo:begin -->';
  const end = '<!-- ubon:demo:end -->';
  const a = readme.indexOf(begin);
  const b = readme.indexOf(end);
  if (a !== -1 && b > a && existsSync(join(root, 'fixtures/demo/after'))) {
    const { text, code } = await demoOutput();
    const why = code === 1 ? 'because there are blocking findings' : 'because there are no blocking findings';
    const block = `${begin}\n\`\`\`text\n$ npx ubon check\n${text.trimEnd()}\n\`\`\`\n\nThe exit code is ${code} ${why}. This output is generated from [fixtures/demo](fixtures/demo), where \`before/\` is the base commit and \`after/\` is what an agent changed.\n${end}`;
    outputs.set('README.md', `${readme.slice(0, a)}${block}${readme.slice(b + end.length)}`);
  }
}

// ---------------------------------------------------------------------------
// llms.txt and llms-full.txt

const DOCS = [
  ['README.md', 'Overview', 'What Ubon checks, how to install it for each agent, and its commands.'],
  ['docs/agents.md', 'For agents', 'What an agent does with Ubon: when to run what, how to read findings, how to fix or suppress them, and what never to do.'],
  ['docs/getting-started.md', 'Getting started', 'Install Ubon and watch it stop an agent in an example app.'],
  ['docs/config.md', 'Configuration', 'Every key of ubon.json, suppressions, and baselines.'],
  ['docs/output.md', 'Output', 'Text, agent, JSON, SARIF, and Markdown formats, exit codes, and fingerprints.'],
  ['docs/ci.md', 'CI', 'The GitHub Action, other CI systems, SARIF upload, and git hooks.'],
  ['docs/mcp.md', 'MCP server', 'Client configuration and the check, explain, map, and vet tools.'],
  ['docs/how-it-works.md', 'How it works', 'Scope, file contexts, sessions, and why some rules only warn.'],
  ['docs/security.md', 'Security', 'The threat model for Ubon itself and how releases are built.'],
  ['docs/compatibility.md', 'Compatibility', 'Node.js, Git, operating systems, and agent versions.'],
  ['docs/upgrade.md', 'Upgrade from Ubon 3', 'Commands, options, configuration, and files that changed.'],
  ['docs/integrations/claude-code.md', 'Claude Code', 'The plugin, its hooks, the skill, and commands.'],
  ['docs/integrations/codex.md', 'Codex', 'Hooks and the skill for Codex.'],
  ['docs/integrations/cursor.md', 'Cursor', 'Hooks and the skill for Cursor.'],
  ['docs/integrations/gemini-cli.md', 'Gemini CLI', 'Hooks and the skill for Gemini CLI.'],
  ['docs/integrations/github-copilot.md', 'GitHub Copilot', 'Hooks for Copilot CLI and the cloud agent.'],
  ['docs/integrations/other-agents.md', 'Other agents', 'The skill, AGENTS.md, git hooks, and MCP for agents without hooks.'],
  ['skills/ubon/SKILL.md', 'The ubon skill', 'The skill agents load: when to check, how to triage, and the playbooks.'],
];

{
  const lines = ['# Ubon', '', '> Ubon checks the work of coding agents. It runs in agent hooks (Claude Code, Codex, Cursor, Gemini CLI, GitHub Copilot), git hooks, and CI, and reports leaked secrets, trust-boundary bugs, missing data access policies, risky packages and commands, and weakened tests. It is deterministic and local.', ''];
  lines.push('Run `npx ubon check` to check the changes since the base branch. Exit code 1 means there is a `block` finding. Fix every `block` finding before you finish a task; `ubon explain <rule>` shows how.', '');
  lines.push('## Docs', '');
  for (const [path, title, description] of DOCS) lines.push(`- [${title}](${BLOB}/${path}): ${description}`);
  lines.push('', '## Rules', '');
  for (const rule of RULES) lines.push(`- [${rule.meta.id}](${BLOB}/docs/rules/${rule.meta.id}.md): ${rule.meta.title} (${rule.meta.level}).`);
  lines.push('', '## Optional', '', `- [Full text of the docs](${BLOB}/llms-full.txt): every page above in one file.`, `- [Changelog](${BLOB}/CHANGELOG.md)`, '');
  outputs.set('llms.txt', lines.join('\n'));
}

{
  const parts = [];
  const pages = [...DOCS.map(([p]) => p), 'docs/rules/README.md', ...RULES.map((r) => `docs/rules/${r.meta.id}.md`)];
  for (const page of pages) {
    const text = outputs.get(page) ?? (existsSync(join(root, page)) ? readFileSync(join(root, page), 'utf8') : null);
    if (text === null) continue;
    parts.push(`<!-- ${page} -->\n\n${text.replace(`${GENERATED}\n\n`, '').trim()}\n`);
  }
  outputs.set('llms-full.txt', parts.join('\n'));
}

// ---------------------------------------------------------------------------
// Write or compare

let stale = 0;
const expectedRulePages = new Set([...outputs.keys()].filter((p) => p.startsWith('docs/rules/')));
if (existsSync(join(root, 'docs/rules'))) {
  for (const file of listFilesRecursive(join(root, 'docs/rules'))) {
    const path = `docs/rules/${file}`;
    if (!expectedRulePages.has(path)) {
      if (check) {
        console.error(`gen-docs: ${path} has no rule; delete it or run npm run gen`);
        stale++;
      } else rmSync(join(root, path));
    }
  }
}
for (const [path, content] of outputs) {
  const full = join(root, path);
  const current = existsSync(full) ? readFileSync(full, 'utf8') : null;
  if (current === content) continue;
  if (check) {
    console.error(`gen-docs: ${path} is out of date; run npm run gen`);
    stale++;
    continue;
  }
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
  console.log(`gen-docs: wrote ${path}`);
}
if (!check) removeEmptyDirs(join(root, 'docs/rules'));
if (check && stale > 0) process.exit(1);
if (check) console.log(`gen-docs: ${outputs.size} files up to date`);

function removeEmptyDirs(dir) {
  if (!existsSync(dir)) return;
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      removeEmptyDirs(full);
      if (readdirSync(full).length === 0) rmSync(full, { recursive: true });
    }
  }
}
